/// Approved public API surface for `XanoRealtime`.
///
/// Completeness tests compare a source scan against ``symbols``. Do not edit
/// this set by hand. When an API change is approved, regenerate with
/// `REGENERATE_PUBLIC_API_INVENTORY=1 swift test --filter scannedPublicAPIMatchesApprovedInventory`.
enum PublicAPIInventory {
    // MARK: - Properties

    /// Approved public type, member, and enum-case keys.
    ///
    /// Types are bare names. Members use `Type.name` for properties and cases.
    /// Functions, initializers, and subscripts use Swift selector form
    /// (`Type.name(_:)`, `Type.init(label:)`, `Type.subscript(key:)`).
    static let symbols: Set<String> = [
        "ChannelOptions",
        "ChannelOptions.catchUpOnForeground",
        "ChannelOptions.history",
        "ChannelOptions.init(history:presence:catchUpOnForeground:)",
        "ChannelOptions.presence",
        "ConnectionState",
        "ConnectionState.connected",
        "ConnectionState.connecting",
        "ConnectionState.disconnected",
        "ConnectionState.reconnecting",
        "JSONValue",
        "JSONValue.array",
        "JSONValue.bool",
        "JSONValue.decode(as:)",
        "JSONValue.double",
        "JSONValue.encode(to:)",
        "JSONValue.init(encoding:)",
        "JSONValue.init(from:)",
        "JSONValue.int",
        "JSONValue.null",
        "JSONValue.object",
        "JSONValue.string",
        "JSONValue.subscript(index:)",
        "JSONValue.subscript(key:)",
        "PresenceChange",
        "PresenceChange.join",
        "PresenceChange.leave",
        "RealtimeEvent",
        "RealtimeEvent.connected",
        "RealtimeEvent.disconnected",
        "RealtimeEvent.error",
        "RealtimeEvent.history",
        "RealtimeEvent.message",
        "RealtimeEvent.presenceFull",
        "RealtimeEvent.presenceUpdate",
        "RealtimeEvent.unhandled",
        "RealtimeMessage",
        "RealtimeMessage.authenticated",
        "RealtimeMessage.channel",
        "RealtimeMessage.payload",
        "RealtimeMessage.sender",
        "RealtimeMessage.socketId",
        "RealtimePeer",
        "RealtimePeer.extras",
        "RealtimePeer.permissions",
        "RealtimePeer.socketId",
        "RealtimePermissions",
        "RealtimePermissions.dboID",
        "RealtimePermissions.rowID",
        "WebSocketCloseCode",
        "WebSocketCloseCode.abnormalClosure",
        "WebSocketCloseCode.badGateway",
        "WebSocketCloseCode.init(rawValue:)",
        "WebSocketCloseCode.internalError",
        "WebSocketCloseCode.normalClosure",
        "WebSocketCloseCode.rawValue",
        "WebSocketCloseCode.reconnectRequested",
        "WebSocketCloseCode.serviceRestart",
        "WebSocketCloseCode.shouldReconnect",
        "WebSocketCloseCode.tryAgainLater",
        "WebSocketCloseCode.unknown",
        "XanoRealtimeChannel",
        "XanoRealtimeChannel.events",
        "XanoRealtimeChannel.leave()",
        "XanoRealtimeChannel.message(_:to:)",
        "XanoRealtimeChannel.name",
        "XanoRealtimeChannel.options",
        "XanoRealtimeChannel.presence",
        "XanoRealtimeChannel.requestHistory()",
        "XanoRealtimeChannel.send(_:authenticated:)",
        "XanoRealtimeClient",
        "XanoRealtimeClient.channel(_:options:)",
        "XanoRealtimeClient.connect()",
        "XanoRealtimeClient.connectionState",
        "XanoRealtimeClient.currentConnectionState",
        "XanoRealtimeClient.disconnect()",
        "XanoRealtimeClient.enterBackground()",
        "XanoRealtimeClient.enterForeground()",
        "XanoRealtimeClient.init(configuration:)",
        "XanoRealtimeClient.setAuthToken(_:)",
        "XanoRealtimeConfiguration",
        "XanoRealtimeConfiguration.apiGroupBaseUrl",
        "XanoRealtimeConfiguration.automaticLifecycleHandling",
        "XanoRealtimeConfiguration.connectionCanonical",
        "XanoRealtimeConfiguration.connectionHash",
        "XanoRealtimeConfiguration.eventBufferSize",
        "XanoRealtimeConfiguration.init(instanceBaseUrl:apiGroupBaseUrl:connectionCanonical:connectionHash:realtimeAuthToken:pingInterval:pingTimeout:queueOfflineActions:automaticLifecycleHandling:eventBufferSize:)",
        "XanoRealtimeConfiguration.instanceBaseUrl",
        "XanoRealtimeConfiguration.pingInterval",
        "XanoRealtimeConfiguration.pingTimeout",
        "XanoRealtimeConfiguration.queueOfflineActions",
        "XanoRealtimeConfiguration.realtimeAuthToken",
        "XanoRealtimeError",
        "XanoRealtimeError.connectionClosed",
        "XanoRealtimeError.decodingFailed",
        "XanoRealtimeError.encodingFailed",
        "XanoRealtimeError.errorDescription",
        "XanoRealtimeError.invalidConfiguration",
        "XanoRealtimeError.notConnected",
        "XanoRealtimeError.pingTimedOut",
        "XanoRealtimeError.server"
    ]
}
